---
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: visit-history-web
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    env_file:
      - ./ENV/.env.app
    # environment:
      # - REDIS_HOST=redis

    # depends_on:
      # - redis


  # redis:
  #   image: redis:6-alpine
  #   command: redis-server --appendonly yes
  #   restart: always

  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10m"
  #       max-file: "5"

  #   volumes:
  #     - redis_data:/data


  ## NGINX-LE  https://github.com/nginx-le/nginx-le
  nginx:
    image: umputun/nginx-le:latest
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
      - ./etc/ssl:/etc/nginx/ssl
      ## NOTE: Ensure to copy 'etc/service-example.conf' to 'etc/nginx/service-visit-history.conf' and modify it
      - ./etc/nginx/service-visit-history.conf:/etc/nginx/service.conf
      # - ./etc/service-example.conf:/etc/nginx/service.conf
      # - ./etc/service-example-2.conf:/etc/nginx/service2.conf  # more services, should be service*.conf
      # - ./etc/stream-example-2.conf:/etc/nginx/stream2.conf  # more streams, should be stream*.conf
      # - ./etc/conf.d:/etc/nginx/conf.d-le  # configuration folder, all files from it will be added
      # - ./etc/stream.conf:/etc/nginx/stream.conf.d-le  # streams configuration folder, all files from it will be added

    ports:
      - "80:80"
      - "443:443"

    env_file:
      - ./ENV/.env.nginx  # NOTE: Ensure to set LE_EMAIL and LE_FQDN variables
    environment:
      - TZ=UTC
      - LETSENCRYPT=true
      # - LE_EMAIL=name@example.com
      # - LE_FQDN=example.com,www.example.com
      ## - SSL_CERT=le-crt.pem
      ## - SSL_KEY=le-key.pem
      ## - SSL_CHAIN_CERT=le-chain-crt.pem

    depends_on:
      - web


# volumes:
#   redis_data:
