---
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: visit-history-web
    env_file:
      - ./.env.example
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:1-alpine
    volumes:
      - ./etc/nginx/templates:/etc/nginx/templates
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  redis_data:
