---
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: visit-history-web-dev
    command: python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn visit_history.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app/mount:ro
    env_file:
      - ./.env.example
    environment:
      - REDIS_HOST=redis
      - DEBUG=1
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes --loglevel debug
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
