---
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: visit-history-web-dev
    command: uvicorn visit_history.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app/mount:ro
    env_file:
      - ./.env.example
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
